<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Connected Services\OData Service\OData ServiceCsdl.xml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Connected Services\OData Service\OData ServiceCsdl.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Identity.Client" Version="4.87.0" />
    <PackageReference Include="Microsoft.OData.Client" Version="8.4.4" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="WorkZone.OData4.Client" Version="26.0.1018" />
  </ItemGroup>

</Project>
